name: ${project.name}
version: ${manifest.version}
main: pl.zekq.shulkerElevator.ShulkerElevator
author: zekq
api-version: '1.21'
folia-supported: true

commands:
  elevator:
    description: Main command for ShulkerElevator
    usage: /elevator debug
